name = "adglent"
version = "1.2.0"

description = "Advent of code helper - automating setup of tests, solution template and problem input"
licences = ["Apache-2.0"]
repository = { type = "github", user = "JohnBjrk", repo = "adglent" }

internal_modules = ["adglent/priv", "adglent/priv/*", "showtime/internal/*"]
gleam = ">= 1.5.0"

[dependencies]
gleam_stdlib = "~> 0.41"
simplifile = "~> 2.2"
gleam_http = "~> 3.7"
gleam_erlang = "~> 0.28"
gleam_otp = "~> 0.13"
gleam_community_ansi = "~> 1.4"
glint = "~> 1.1"
gap = "~> 1.1"
snag = "~> 0.3.0"
tom = "~> 1.1"
gleam_httpc = "~> 3.0"
# showtime = "~> 0.2"

[dev-dependencies]
gleeunit = "~> 1.2"
