name = "adglent"
version = "1.2.0"

description = "Advent of code helper - automating setup of tests, solution template and problem input"
licences = ["Apache-2.0"]
repository = { type = "github", user = "JohnBjrk", repo = "adglent" }

internal_modules = [
  "adglent/priv",
  "adglent/priv/*",
  "showtime/internal/*",
]
gleam = ">= 1.0.0"

[dependencies]
gleam_stdlib = "~> 0.36"
simplifile = "~> 1.5"
gleam_http = "~> 3.6"
gleam_erlang = "~> 0.24"
gleam_otp = "~> 0.10"
gleam_community_ansi = "~> 1.4"
glint = "~> 0.18.0"
gap = "~> 1.1"
snag = "~> 0.3.0"
tom = "~> 0.3.0"
gleam_httpc = "~> 2.1"
# showtime = "~> 0.2"

[dev-dependencies]
gleeunit = "~> 1.0"
